apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksworkshop297-af4a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksworkshop297-af4a"
  template:
    metadata:
      labels:
        app: "aksworkshop297-af4a"
    spec:
      containers:
        - name: "aksworkshop297-af4a"
          image: "acr4824.azurecr.io/aksworkshop297"
          ports:
          - containerPort: 80