on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acr4824.azurecr.io
        username: ${{ secrets.acr_acr4824_username }}
        password: ${{ secrets.acr_acr4824_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/dockeragent" -f  "dockeragent/Dockerfile" -t acr4824.azurecr.io/aksworkshop297:${{ github.sha }} --label dockerfile-path=dockeragent/Dockerfile
        docker push acr4824.azurecr.io/aksworkshop297:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksworkshop297_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksworkshop-297ab71 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksworkshop-297ab71`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksworkshop-297ab71
        container-registry-url: acr4824.azurecr.io
        container-registry-username: ${{ secrets.acr_acr4824_username }}
        container-registry-password: ${{ secrets.acr_acr4824_password }}
        secret-name: aksworkshop2dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksworkshop-297ab71
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acr4824.azurecr.io/aksworkshop297:${{ github.sha }}
        imagepullsecrets: |
          aksworkshop2dockerauth
